description: "Removed high correlated features >= .95"
experiment: exp_005_removed_high_correlated_features 

family: ad_xgb_wl_delta
seeds: [13, 23, 37]

hidden_dims: [64, 32]
dropout: 0.3
activation: ReLU

lr: 0.001
weight_decay: 0.0001
batch_size: 64
epochs: 150
patience: 20

features_to_drop: [
    "current_goal_l2_min",
    "pred_goal_l2_min",
    "pred_goal_l2_final",
    "pred_goal_l2_mean",
    "pred_goal_l2_std",
    "pred_goal_l2_max",
    "current_goal_l2_max",
    "pred_norm_min",
    "pred_norm_max",
    "pred_norm_final",
]

features_added: [] 

device: auto
verbose: false

